"jobs":
  "homeassistant":
    "needs": []
    "runs-on": "ubuntu-latest"
    "steps":
    - "uses": "actions/checkout@v1"
    - "name": "Build homeassistant"
      "run": |
        docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }} quay.io
        docker build -f homeassistant/Dockerfile -t quay.io/johannweging/homeassistant:latest ./homeassistant
        docker push quay.io/johannweging/homeassistant:latest
  "terraform":
    "needs": []
    "runs-on": "ubuntu-latest"
    "steps":
    - "uses": "actions/checkout@v1"
    - "name": "Build terraform"
      "run": |
        docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }} quay.io
        docker build -f terraform/Dockerfile -t quay.io/johannweging/terraform:latest ./terraform
        docker push quay.io/johannweging/terraform:latest
  "vault2env":
    "needs": []
    "runs-on": "ubuntu-latest"
    "steps":
    - "uses": "actions/checkout@v1"
    - "name": "Build vault2env"
      "run": |
        docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }} quay.io
        docker build -f vault2env/Dockerfile -t quay.io/johannweging/vault2env:latest ./vault2env
        docker push quay.io/johannweging/vault2env:latest
"name": "Build Docker Images"
"on":
  "push": {}
  "schedule":
  - "cron": "0 12 * * THU"
